### ISSUE TITLE
Mounting: mount appearing to persist after process exit

### ISSUE THREAD

**Issue by lsileoni** [HeyPuter/puter-fuse#1]
The investigation to this issue began when I was running `puter-fuse` and the API started responding with a bunch of  `5xx` errors.

After exiting the process, it appeared as if `/tmp/mnt` stays mounted/in a buggy state and any further usage of `puter-fuse` results in the following error:

```
[]
WARNING: fileReadCacheTTL DEFAULTS TO 30s
panic: mkdir /tmp/mnt: file exists

goroutine 1 [running]:
main.main()
	/home/username/Documents/puter-fuse/main.go:251 +0x16fe
```

When I `ls -la | grep mnt` the directory, it gives me the following output, which I'm not sure if is just a normal mount state or something else.

```
ls -la /tmp | grep mnt
ls: cannot access '/tmp/mnt': Transport endpoint is not connected
d?????????  ? ?        ?            ?            ? mnt
```

Running `umount /tmp/mnt` appears to resolve the issue and allow `puter-fuse` to run normally again. With  `ls -la | grep mnt` giving:
```
drwxr-xr-x  0 root     root         0 Jan  1  1970 mnt
```

However, now if I attempt to `SIGINT` the process to stop it, the same issue keeps occurring, only being resolved when I manually unmount the directory.

What appears to work for me as a temporary fix to this issue is defining a function `UnmountDirectory` in `main.go`

```go
func UnmountDirectory(path string) {
    cmd := exec.Command("umount", path)
    if err := cmd.Run(); err != nil {
		panic(fmt.Errorf(("error unmounting directory: %s"), err))
    }
}
```

and having that be `defer`:ed in the main function right after a successful mount and having it also be called prior to actually checking if the directory exists with `MkdirAll`.

Additionally, I defined a function for registering a signal handler for `SIGINT` so it could be handled gracefully like so

```go
func RegisterSignals(mountPoint string) {
	sig := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT)
	go func() {
        	<-sig
        	fmt.Println("\nSIGINT received, terminating gracefully...")
		UnmountDirectory(mountPoint)
        	os.Exit(0)
	}()
}
```

I register this handler right after the first `UnmountDirectory` call. With both of these changes, it seems like no matter what I do with `puter-fuse`, it doesn't get into the state where `/tmp/mnt` remains mounted after normal termination of the program.

Please do note, that I haven't written much Go prior to this and that I'm not familiar with Go idioms(though I have experience writing Unix software). The snippets are suggestions and what I wrote to fix the issue for me locally.

```
OS: Linux 6.7.8-arch1-1
Go version: go1.22.1 linux
Arch: AMD64
```

**Comment by KernelDeimos** [comment]
It's fixed now - thanks for reporting this!

![image](https://github.com/HeyPuter/puter-fuse/assets/7225168/3e566ba9-698c-49af-a7b3-b3c80f19e98a)
