### ISSUE TITLE
Mount fail

### ISSUE THREAD

**Issue by stretch07** [HeyPuter/puter-fuse#2]
![image](https://github.com/HeyPuter/puter-fuse/assets/78528552/55993faf-2512-43a5-a38c-782c6c33a8e7)
Unfortunately I have no clue what causes this.

**Comment by KernelDeimos** [comment]
These looks like compiler errors within the `hanwen/go-fuse` dependency. The repository hasn't been updated in a while so it seems unlikely a bug was introduced. What version of golang do you have installed? I'm testing with version `1.22.0`

**Comment by stretch07** [comment]
Huh, that's strange. I'm using `go version go1.22.1 windows/amd64`.
I'm on Windows 11 and I downloaded from `https://dl.google.com/go/go1.22.1.windows-amd64.msi`.

**Comment by KernelDeimos** [comment]
Oh I think I know what's going on now. FUSE drivers won't work in Windows. Try it under WSL
